Remove support for filtering on EB entity ID
OpenConext/OpenConext-profile pull request #172
Opened 2021-06-22 16:25 UTC by Badlapje

Prior to this change, the filtering was needed for the generic "these entity ids should be filtered problem".  Given that the special cased entity has been removed from EB, this is no longer needed.

This change removes the filtering.

Pivotal ticket @ https://www.pivotaltracker.com/story/show/111038134

2021-06-23 08:30 UTC, thijskh requested changes
Do I now only see the removal of the parameter, not of the actual filtering?

2021-06-24 09:12 UTC, Badlapje commented
> Do I now only see the removal of the parameter, not of the actual filtering?

As far as i can see the `parseEngineBlockEntityIdConfiguration` method is the filtering?  If not I'm missing something.  I don't see anything else happening involving the engineblock entity ID.  

With regards to filtering: there's an AttributeFilter class, but that doesn't seem to do anything with the entityID?

2021-07-20 08:17 UTC, thijskh requested changes
I am more confused now than I was before this PR. It seems that the engine block entity ID is also used in the process to determine the user's actual IdP (walk AuthenticatingAuthority and exclude EB). So we cannot drop the configuration. I cannot find that Profile currently does something specific with excluding the EB from the consent iist at all. So maybe we can just close this task altogether :woman_shrugging:

2021-07-22 12:48 UTC, Badlapje commented
@MKodde & @pablothedude do you guys have any insights on this?  This requires more knowledge of the inner mechanics of EB & Profile than i possess at the moment.

2021-10-04 15:08 UTC, thijskh commented
Let's just close it. No value to be gained it seems.

2021-10-04 15:08 UTC, closed without merging